version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/typescript-node
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=flexspotff,flexspotff_test,flexspotff_com_d1f3
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data