-- AlterTable
ALTER TABLE "Team" ADD COLUMN     "medianLosses" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "medianTies" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "medianWins" INTEGER NOT NULL DEFAULT 0;
